[build]
  publish = "public"
  functions = "functions"

[functions]
  external_node_modules = ["express", "cors", "serverless-http"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
